--liquibase formatted sql

--changeset mahmoud:000-create-event-schema
CREATE SCHEMA IF NOT EXISTS event;

--rollback DROP SCHEMA IF EXISTS event;

--changeset mahmoud:001-create-event
CREATE TABLE event
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR   NOT NULL,
    state       VARCHAR   NOT NULL,
    description VARCHAR   NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--rollback DROP TABLE IF EXISTS event;
